name:                my-project
version:             0.1.0.0
github:              "githubuser/my-project"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/my-project#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- servant-auth-server
- protolude
- network-uri
- containers
- lens
- wai

library:
  source-dirs: 
  - core
  - client/shared
  dependencies:
  - mtl
  - servant
  - servant-auth
  - aeson
  - lucid
  - miso
  - text
  - hedis
  - selda
  - selda-sqlite
  - selda-postgresql
  - bloodhound
  - template-haskell
  - exceptions
  - clay
  - http-media

executables:
  my-project-exe:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-project
    - warp
    - wai-logger
 
tests:
  my-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-project
    - hspec
    - hspec-wai
    - hspec-wai-json
    - http-types
    - jose
    - text
    - bytestring
    - lucid
    