version: 2
jobs:
  build_project:
    docker:
      - image: haskell:8.4.3
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
    steps:
      - checkout
      - restore-cache:
          keys: stack-work-{{checksum "stack.yaml"}}-{{checksum "package.yaml"}}      
      - run: sudo apt-get install libpq-dev
      - run: stack setup
      - run: stack build
      - run: stack test
      - save_cache:
          key: stack-work-{{checksum "stack.yaml"}}-{{checksum "package.yaml"}}
          paths:
            - ".stack-work"
  build_client:
    machine: true
    steps:
      - checkout
      - run: sudo mkdir -p /nix
      - run: sudo chown circleci /nix
      - run: curl https://nixos.org/nix/install | sh
      - run: echo "source /home/circleci/.nix-profile/etc/profile.d/nix.sh" >> ~/.bash_profile
      - run: source ~/.bash_profile && cd client && nix-build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_project
      #- build_client