version: 2
jobs:
  build_project:
    machine: true
    steps:
      - checkout
      - restore-cache:
          keys:
            - stack-{{ checksum "stack.yaml" }}
      - restore-cache:
          keys:
            - stack-{{checksum "stack.yaml"}}-{{checksum "package.yaml"}}
      - run: wget https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz -O /tmp/stack.tar.gz
      - run: sudo mkdir /tmp/stack-download
      - run: sudo tar -xzf /tmp/stack.tar.gz -C /tmp/stack-download
      - run: sudo chmod +x /tmp/stack-download/stack-1.7.1-linux-x86_64/stack
      - run: sudo mv /tmp/stack-download/stack-1.7.1-linux-x86_64/stack /usr/bin/stack   
      - run: sudo add-apt-repository 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main'
      - run: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add - && sudo apt-get update   
      - run: wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu55_55.1-7ubuntu0.4_amd64.deb -P /tmp/
      - run: sudo dpkg -i /tmp/libicu55_55.1-7ubuntu0.4_amd64.deb
      - run: sudo apt-get install postgresql-common  libsystemd0 postgresql-10
      - run: stack setup
      - run: stack test
      - save-cache:
          key: stack-{{ checksum "stack.yaml" }}
          paths:
            - "~/.stack"
      - restore-cache:
          keys: stack-{{checksum "stack.yaml"}}-{{checksum "package.yaml"}}
          paths:
            - ".stack-work"
  build_client:
    machine: true
    steps:
      - checkout
      - run: sudo mkdir -p /nix
      - run: sudo chown circleci /nix
      - run: curl https://nixos.org/nix/install | sh
      - run: echo "source /home/circleci/.nix-profile/etc/profile.d/nix.sh" >> ~/.bash_profile
      - run: source ~/.bash_profile && cd client && nix-build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_project
      #- build_client